DROP FUNCTION jsonb_minus(JSONB, TEXT[]) CASCADE;
DROP FUNCTION jsonb_minus(JSONB, JSONB) CASCADE;
DROP FUNCTION jsonb_extract(JSONB, TEXT[]) CASCADE;
DROP FUNCTION table_pk_columns(REGCLASS) CASCADE;
DROP SCHEMA audit CASCADE;
